//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Img
    {
        public int img_id { get; set; }
        [DisplayName("ชื่อภาพ")]
        public string img_name { get; set; }
        [DisplayName("คำอธิบาย")]
        public string img_description { get; set; }
        [DisplayName("หมวดหมู่")]
        public string img_category { get; set; }
        [DisplayName("เจ้าของ")]
        public string UserName { get; set; }
        [DisplayName("รูป")]
        public string img_url { get; set; }
        [DisplayName("วันที่อัพโหลด")]
        public Nullable<System.DateTime> img_date { get; set; }
    }
}
