//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img
    {
        public int img_id { get; set; }
        public string img_name { get; set; }
        public string img_description { get; set; }
        public string img_category { get; set; }
        public string UserName { get; set; }
        public string img_url { get; set; }
        public Nullable<System.DateTime> img_date { get; set; }
    }
}
